### ISSUE TITLE
Run PHP with -d parameters

### ISSUE THREAD

**Issue by Mechazawa** [paratestphp/paratest#212]
Right now the PHPUnit executable is called directly by the application. This means that `/usr/bin/env php` is implicitly used to execute php. It would be great to have a parameter that allows us to set uptional ini parameters. Such as `-d zend_extension=xdebug.so`. Since XDebug isn't always loaded in on every system by default and is sometimes only used to get coverage information.

A way of implementing this would be to add an optional parameter and prepending `/usr/bin/env php -d foo=bar -d baz=tor` to the command. Currently running paratests with `-d zend_extension=xdebug.so` does not carry over to the subprocesses it spawns. 

``` php
// Something like this should do the job
$this->addOption('set-ini', 'd', InputOption::VALUE_IS_ARRAY | InputOption::VALUE_OPTIONAL, 
                 'Set php ini params before execution (ex: -d zend_extension=xdebug.so)');`
```

Something like `--load-extension xdebug.so` would also be good.

**Comment by dominics** [comment]
As long as you're using the standard runner, it should be possible (albeit annoying) as a workaround to create a small script that does `exec php -dzend_extension=xdebug.so phpunit`. You name it phpunit-wrapper (or similar) and get paratest to call it using the `--phpunit=path/to/phpunit-wrapper` command line option.

Unfortunately, this workaround seems to be broken for the `WrapperRunner`, which uses a hard-coded phpunit wrapper that can't be changed: https://github.com/brianium/paratest/blob/master@{2016-06-27}/src/ParaTest/Runners/PHPUnit/WrapperRunner.php#L46

BTW, I vote :-1: for `--load-extension`, because my use case is `-dmemory_limit`; I'd be good to keep this more generic (the WrapperRunner problem above affects *any* `-d` flag, because an actual PHP process is no longer seeing $argv I think...)

**Comment by KarimGeiger** [comment]
I'd appreciate this feature as well.

**Comment by jmalinens** [comment]
+1

**Comment by latvianization** [comment]
+1

**Comment by paslandau** [comment]
https://github.com/paratestphp/paratest/pull/361 just got merged into master. Please check if you can use that as a "generic" workaround:

```
php '-d' 'zend_extension=xdebug.so' bin/paratest -p 4 --coverage-text test/unit --passthru-php="'-d' 'zend_extension=xdebug.so' "

```
See docs/code-coverage.md for a more in-depth usage example.

**Comment by andreasschroth** [comment]
@paslandau is right, so I close this issue.
