### ISSUE TITLE
TEST_TOKEN's are indexed differently by Runner and WrapperRunner

### ISSUE THREAD

**Issue by notclive** [paratestphp/paratest#213]
When using the Runner the TEST_TOKEN is a number between 0 and the number of processes - 1.

When using the WrapperRunner the TEST_TOKEN is a number between 1 and the number of processes.

We have a test suite which use a mix of Runner and WrapperRunner, this means that we have to provision one more database than necessary.

**Comment by michaelbutler** [comment]
The fix for this is simple, I'm working on it presently. However confirming it via a unit or functional test is a bit tricky. My idea is to use a custom phpunit xml file with a custom test listener that logs to a file the TEST_TOKEN environment parameter. Then the functional test checks the file when the suite is finished, and confirms that the tokens are always 1, 2, .... n where `n` is the number of max processes used. 

Just curious though, which would you prefer -- starting all indexes at zero (the Runner style) or starting at 1 (the WrapperRunner style)?

**Comment by notclive** [comment]
I would suggest starting at 1. That way `getenv('TEST_TOKEN')` always returns a truthy value.

**Comment by Slamdunk** [comment]
Closed by https://github.com/paratestphp/paratest/pull/285
