### ISSUE TITLE
restructure build

### ISSUE THREAD

**Issue by julianseeger** [paratestphp/paratest#258]
* coverage should be pushed only from one (and always the same) job
* php-cs-fixer (depends on #256) should run in a different stage (makes it easier to tell if test tests or the check failed)

**Comment by Slamdunk** [comment]
I've deeped down [Travis build stages](https://docs.travis-ci.com/user/build-stages):

> Build stages is a way to group jobs, and run jobs in each stage in parallel, but run one stage after another sequentially.

I see no advantage in using them, there is no job that depends on another one.
As soon as #256 is merged I'll create a PR with a restructured `.travis.yml` with a better variable handling, but without stages because the two points you listed here can be easily achieved anyway.

**Comment by julianseeger** [comment]
looking forward to see that :D
don't care about stages. It would just be nice to see that the fixer failed instread of the test on the first look

**Comment by Slamdunk** [comment]
https://github.com/brianium/paratest/pull/260

**Comment by andreasschroth** [comment]
Closing this now as the PR got already merged.
