### ISSUE TITLE
Version 1.1.0 not on packagist

### ISSUE THREAD

**Issue by KDederichs** [paratestphp/paratest#295]
The new version doesn't seem to be available on packagist. 
I don't know if that is intended or not :)

**Comment by julianseeger** [comment]
True. This is definitely not intended. I created the release as always via github ... something between packagist and github must have changed since 1.0.1 (2 Jul 2017).

Unfortunately I have no access to paratest in packagist or the integration settings at github so I can't investigate or at least manually upload the release to packagist. @brianium needs to fix this ... or a new maintainer :/

**Comment by julianseeger** [comment]
It's probably some issue with the composer.json. Looks like packagist has hardened it's constraints when validating it. I received some notification in another project that the license was not one from the spec, but for paratest, "MIT" looks good and I can't find any flaws. @brianium might have gotten some mail from packagist

**Comment by michaelgv** [comment]
Fixed, it’s now available
