### ISSUE TITLE
Add paratest log option

### ISSUE THREAD

**Issue by michaelbutler** [paratestphp/paratest#321]
For aesthetics, paratest prints nice progress information (`.`, `E`, `W`, `R`, etc) when running, but the downside is any other output from sub-processes is not shown.
I think it would help developers to have an output log option for paratest to dump all output of every sub-process. It could potentially catch issues and also allow ability to see the SpeedTrapListener output.

For those using jenkins, this could be produced as a build artifact to debug issues in test runs.

**Comment by paslandau** [comment]
@michaelbutler 
I just prepared a PR https://github.com/paratestphp/paratest/pull/363 that creates a logfile per process in the tmp directory if the enovironment variable `PT_LOGGING_ENABLE` is set, e.g. via
```
export PT_LOGGING_ENABLE="true" 
```
Currently only for `--runner WrapperRunner` as I found those the hardest to debug. Since the inter-process-communication is kinda hard to understand I opted for the environment-variable way to avoid unnecessary breaking changes.

Docs https://github.com/paslandau/paratest/blob/wrapper-runner-log/docs/logging.md
