### ISSUE TITLE
Corresponding phpunit.xml argument for --runner?

### ISSUE THREAD

**Issue by mkarnicki** [paratestphp/paratest#357]
Is there a configuration I could set in phpunit.xml instead of passing --runner WrapperRunner to paratest manually? Thank you, amazing project!

**Comment by paslandau** [comment]
Since `phpunit.xml` comes from a different project, I don't think that this makes much sense (as it would couple phpunit to paratest).

A better solution would imho be to introduce a `paratest.xml` that acts as the default configuration for `paratest` and would let you configure default values for every option on `paratest`.

Thoughts?

**Comment by andreasschroth** [comment]
@paslandau Yep, sounds reasonable to me, although I'm not absolutely sure if it wouldn't be overkill. Imo, it's pretty easy to pass the command line options and create an alias or small shell script, etc. for it.
