### ISSUE TITLE
Feature request: Support phpunit's --testdox option

### ISSUE THREAD

**Issue by AchoArnold** [paratestphp/paratest#396]
Feature request: Support phpunit's --testdox option

It will be nice to see the info about the current test(s) which are bieng run.

**Comment by andreasschroth** [comment]
From the number of thumbs I can see that this feature is requested a lot from our community.

Thus, I gave it the priority label and will try to implement it. I cannot give an exact timeline though, sorry. PRs are also welcome.

**Comment by Slamdunk** [comment]
So, here's the thing: what PHPUnit does cannot be replicated by ParaTest exactly the same way, because `\PHPUnit\Util\TestDox\CliTestDoxPrinter` uses the base Test & TestResult classes, while ParaTest can only use `--testdox-xml` output.

Best we can do is something similar to `--testdox-text` that includes the error messages without the stack trace. I would find them useless: how would you properly debug the failing tests without stack traces?

The useful result we can achieve is supporting both `--testdox-text <file>` and `--testdox-text <file>` (see also https://github.com/paratestphp/paratest/issues/273) though: are them enough?

**Comment by AchoArnold** [comment]
keep-alive

**Comment by Slamdunk** [comment]
TestDox support added in https://github.com/paratestphp/paratest/pull/679

**Comment by AchoArnold** [comment]
Nice to see this feature implemented. Thanks @Slamdunk
