### ISSUE TITLE
Paratest with database transactions

### ISSUE THREAD

**Issue by khrizt** [paratestphp/paratest#399]
Hi,

I just discovered this great package and I'm trying to use it in my job. The things is that tests fail because data in the database is not present. I'm not completely sure, but it looks like as each test has a database transaction (with PostgreSQL) that rolls back when everything is ok, using parallel executions rollbacks data for other test cases.

Has anyone managed to get paratest work with database transactions? Can be that I'm doing something wrong, but if someone has some insight on things I can try, I'd appreciate that.

Thanks

**Comment by andreasschroth** [comment]
Are you sure your tests don't have dependencies among each other? Even hidden ones, e.g. test 2 assumes that test 1 has been executed before with doing something inside the database?

Did you try to run your tests in a random order with phpunit (without paratest being involved)? I would assume that fails also, because probably there are hidden dependencies. But that's just my guess.

**Comment by crzdeveloper** [comment]
Try running tests in functional mode, it might give you some hints about the tests which depend on the results of other tests.

Also what is not clear from your question, how many DB backends do you use while testing? For instance, we run paratest in 8 threads and thus we have 8 DB backends. It means, every test file is executed against one of the DB backends. If you use one DB and more than one thread in paratest, there will be definitely problems in DB unit tests.

**Comment by khrizt** [comment]
Really sorry for the delay in response, I got caught in work and forgot about this.

I made some changes because yes, the tests had hidden dependencies (not from test to test but using the same framework instance) and I soved that.

And yes, I'm using 1 only DB backend, that may be the problem because I still got errors. But I can't totally understand why there are this problems, if every test has his own transaction, in the transaction the test loads the needed fixtures, runs it and rollbacks the transaction. That should leave the DB untouched and should not affect other tests... am I missing something?

**Comment by andreasschroth** [comment]
@khrizt No worries! I'd say it's definitely best practice to use one separate database per process. Otherwise you will definitely encounter at least unexpected behaviour, e.g. failing transactions because no lock is possible and thus rollbacks, dead locks, etc. If you want stable, reliable tests one separate database per process is the only way to go. And I think that's the only way tests are useful: If they're reliable. Otherwise developers in your team will end up ignoring test failures if they happen randomly.

**Comment by khrizt** [comment]
Ok, I'll do some more testing with 1 DB backend (sorry I'm kind of stubborn and want to know exactly why tests are failing), but start working on generating N backends.

And I'll close this issue because this seems to be another problem, not one with paratest and transactions.

Thanks a lot for your help.
