### ISSUE TITLE
phpunit/php-timer version incompatibility

### ISSUE THREAD

**Issue by Maxwell2022** [paratestphp/paratest#443]
"phpunit/phpunit": 9.2.5
"brianium/paratest": 4.0.0

![image](https://user-images.githubusercontent.com/670701/85693774-e0b14200-b719-11ea-9477-b5c3cd19201f.png)

It looks like **paratest** is requiring `phpunit/php-timer` ["^2.0|^3.0"](https://github.com/paratestphp/paratest/blob/4.0.0/composer.json#L10) but **PHPUnit** v9.2 is [requiring ^5.0](https://github.com/sebastianbergmann/phpunit/blob/9.2.5/composer.json#L40)

It changed from **PHPUnit v9.2.0** that was requiring [^4.0](https://github.com/sebastianbergmann/phpunit/blob/9.2.0/composer.json#L40) and then from version **9.2.2** it requires [^5.0](https://github.com/sebastianbergmann/phpunit/blob/9.2.2/composer.json#L40)

**Comment by Zarthus** [comment]
Indeed, we also have this issue. We cannot upgrade to PHPunit 7.2 because there needs to be a release for paratest. (this issue is fixed in dev-master, 22 days ago, in bb0bae9088176cc1c64e8bb94ce9a7058f7bc6fc and 4b1177661d1134b6e53b5590c11d0325cebf3347).
https://github.com/paratestphp/paratest/commits/master/composer.json cc @Slamdunk

**Comment by Slamdunk** [comment]
Yup, already fixed in https://github.com/paratestphp/paratest/pull/440
