### ISSUE TITLE
Builds not passing after PR merges #440 and #438

### ISSUE THREAD

**Issue by cagp-dev-mtl** [paratestphp/paratest#446]
Hello, builds are not passing after PR merges #440 and #438

**Comment by cagp-dev-mtl** [comment]
![image](https://user-images.githubusercontent.com/8563418/86548954-d2c2a480-bf03-11ea-8f92-1d0dbf959cd1.png)

**Comment by andreasschroth** [comment]
According to https://travis-ci.org/github/paratestphp/paratest/builds it's unrelated to any specific PR.

**Comment by TysonAndre** [comment]
```
php '/.../paratest/vendor/phpunit/phpunit/phpunit' '--configuration'     '...g/paratest/phpunit.xml.dist' '--log-junit' '/tmp/PT_M7Gcut' 'test/fixtures/passing-tests/LegacyNamespaceTest.php'
Class 'LegacyNamespaceTest' could not be found in ..../paratest/test/fixtures/passing-tests/LegacyNamespaceTest.php'.
```

Could it be related to a change in PHPUnit itself, enforcing that classes have names matching their files? Only 7.3+ is failing, so the version of phpunit supporting php 7.2 was probably still working.

**Comment by TysonAndre** [comment]
```
bin/paratest test/fixtures/passing-tests

Running phpunit in 8 processes with /.../paratest/vendor/phpunit/phpunit/phpunit

Configuration read from /.../paratest/phpunit.xml.dist

.....
In ResultPrinter.php line 192:
                                                                                                                                                      
  Log file /tmp/PT_M7Gcut is empty. This means a PHPUnit process has crashed.                                                                         
  The process: /.../php-7.4.9-dev-nts-install/bin/php '/..../paratest/vendor/phpunit/phpunit/phpunit' '--configuration'   
  '/..../paratest/phpunit.xml.dist' '--log-junit' '/tmp/PT_M7Gcut' 'test/fixtures/passing-tests/LegacyNamespaceTest.php'         
  This means a PHPUnit process was unable to run "test/fixtures/passing-tests/LegacyNamespaceTest.php"     
```

**Comment by andreasschroth** [comment]
Thanks a lot @TysonAndre for looking into this... Very helpful.

I also believe, probably it's the PHPUnit bug you mentioned... The only thing is: Isn't the purpose of the file https://github.com/paratestphp/paratest/blob/master/test/fixtures/passing-tests/LegacyNamespaceTest.php to provide a test class in the global namespace in order to ensure that this runs through? I mean, it's done on purpose. So we can't move that class into an own namespace, as the test would then not test the current behavior anymore.

I'm not happy with removing this test from the Paratest test suite, but if it's a bug in PHPUnit, maybe we should do that in order to be able to move on.

**Comment by cagp-dev-mtl** [comment]
Thank you very much for looking into this
