### ISSUE TITLE
Support for Gitlab CI parallel processing

### ISSUE THREAD

**Issue by nevets963** [paratestphp/paratest#532]
Gitlab Ci has a feature to run test suites in parallel and has a property to control the concurrency: https://docs.gitlab.com/ee/ci/yaml/#parallel

It works by running the same test command N times and injecting an index (via env variable) into each job so that the test command knows which 'chunk' of the test suite to process. e.g. parallel is set to 3. Process 1 receives index 0, 2 receives index 1 and 3 receives index 2. The env variable is: `CI_NODE_INDEX`

Any ideas how we could make this work with Paratest?

**Comment by Slamdunk** [comment]
Hi, since the duration of each test is unknown, to optimize resources ParaTest distributes tests across processes **while** running, so _statistically_ all processes elapse the same amount of time and end together.

For the feature you are requesting, the test suite should be split **before** parallelizing the runs; that's something that would require a non trivial coding effort.

I know Codeception does this: https://codeception.com/docs/12-ParallelExecution and comes with predefined tools to merge the results.

A recent, still not merged PR against PHPUnit is open in order to reach the goal you are asking for easier: https://github.com/sebastianbergmann/phpunit/pull/4449

At the time of writing, I'm inclined to not support such feature, but any PR is welcome.

**Comment by nevets963** [comment]
Hi @Slamdunk I appreciate the fast response and this makes complete sense. The current architecture makes a lot of sense to optimise how these process the test suite without having 1 process finish early and another process still running, etc.

I understand why you don't want to support and we're going to look at the alternatives to Gitlab CI as we like the way Paratest works :)

I'll close this issue
