### ISSUE TITLE
Custom test suite loaders are ignored

### ISSUE THREAD

**Issue by oneserv-heuser** [paratestphp/paratest#556]
Hello!

I'm trying to get magento 2 integration tests to work with this package. The problem is that it seems like that the phpunit configuration "testSuiteLoaderClass" and "testSuiteLoaderFile" are ignored, But these are two configuration variables which are needed for magento 2 integration tests to run. For reference see [here](https://github.com/magento/magento2/blob/632a7c61dfd6b2bda8159ed294543fcb9bbaa147/dev/tests/integration/phpunit.xml.dist#L15).

My tests are failing because of this and I cannot make them run parallel. I know that using a custom test suite loader is deprecated but phpunit 10 will be released in Feb 2021 and until magento adds support for it, it will take a few years (they recently added phpunit 9 and jumped from phpunit 6...).

So having this feature would really be awesome as magento integration tests are a pain in the ass when it comes to speed. We now need 15min for around 300 tests which is completely inacceptable.

Or do you have any tips on running magento integration tests in parallel? Any help would be really appreciated!

Many greetings

**Comment by Slamdunk** [comment]
As you said, custom `TestSuiteLoader`s have been deprecated in https://github.com/sebastianbergmann/phpunit/issues/4039 and will soon be removed, and I'm not going to commit anything already declared dead.

ParaTest is a runtime parallelization tool: you can still achieve preemptive parallelization with few custom scripts that take `vendor/bin/phpunit --list-tests` output and split them into multiple processes, just like what [Codeception does with Robo](https://codeception.com/docs/12-ParallelExecution#Robo).

**Comment by oneserv-heuser** [comment]
@Slamdunk Thank, I'll have a look at Robo!

**Comment by mfn** [comment]
> As you said, custom `TestSuiteLoader`s have been deprecated

Same applies also to `\PHPUnit\Runner\StandardTestSuiteLoader` which is used in `\ParaTest\Parser\Parser::__construct`.

Do we know the "impact" of this, yet?

**Comment by Slamdunk** [comment]
No but it doesn't matter: `\PHPUnit\Runner\StandardTestSuiteLoader` is marked as `@internal` hence ParaTest owes no promises to its users for it.
For our own implementation it doesn't matter neither: as soon as the new way of doing it will be available, which isn't at the moment, we'll upgrade the codebase with no BC break for ParaTest users: since it's declared `@internal`, we too can change everything whenever we want in any patch version.

**Comment by mfn** [comment]
After some reading I've gone in (good way) circles now here.

First, I didn't realize this was a PR from you ;)

Second, later I found what was referred to as the preferred approach to execute only a selected sub-set of tests: https://github.com/sebastianbergmann/phpunit/pull/4037#issuecomment-584146918 mentions https://github.com/sebastianbergmann/phpunit/issues/3387.

This now were I ended up in (my own) circle, because I submitted a PR for this https://github.com/sebastianbergmann/phpunit/pull/4449 (but I failed to receive some notifications, so not done yet).

The reason I'm lurking around here is that desire/need to for as much efficient parallel execution of potentially massive test suites.

Initially I started out with https://github.com/wizaplace/phpunit-slicer but it used a few internal phpunit classes which all have been deprecated or changed so much, that code does not work at all. It basically did in-memory load the suites, split them accordingly and then ran only a sub-part of it (I might note it does not work correctly in all cases, namely I think data providers, but I'm not 100% sure right now). The "solution" to get this working with recent version of phpunit was to copy paste phpunit classes around and adapted them as intrusive as possible to make the phpunit-slicer work. Obviously we don't need to delve into the downsides here, this isn't 

After that I started to look around and found the previously mentioned issue (https://github.com/sebastianbergmann/phpunit/issues/3387) and figured that yes, this can solve the problem phpunit-slicer is facing: if phpunit can generate a list and also consume a (modified) list of tests to execute, then we've established a _stable_ way to do this.

### Now why would I use paratest and/or phpunit-slicer?

- design of phpunit-slicer: separate processes manually launched, each (single) process runs a different slice
  - can be run on a single machine but also distributed on multiple machines (*)
    ("multiple machines" => using test matrix like travis/github actions provide)
- design of paratest: multiple processes launched on a single machine
  - can use a single machine to it's fullest power (i.e. multiple cores)

When I look at the contemporary CI offerings, we get machines with 2 cores, which means to me:
- phpunit-slicer can use multiple machines but only 1 core
- paratest can use a single machine and multiple cores

Ideally we could run "a thing" which:
- you can distribute over multiple machines
- can use multiple cores

Apologies for the sudden brain dump here, I'm exploring the landscape regarding this for some time, trying to find the most efficient solution(s).

(*) It is possible to run phpunit-slicer multiple times on a single machine using background jobs and such, but this gets very messy with current CI offerings regarding outout logging and would require more work; though I might pursue this too.

**Comment by Slamdunk** [comment]
Hi, your concerns about exploiting at best multiple hosts with multiple cores are understandable.

In order to squeeze the most out of a multi machine env, which needs preemptive splitting, I suggest to have a local ParaTest run with JUnit log enabled, which traces the execution time of every test, and split tests with same average total elapsed time.

BTW, as soon as https://github.com/sebastianbergmann/phpunit/pull/4449 gets merged, we can implement it here too.
