### ISSUE TITLE
`--version` does not return SemVer version of neither Paratest nor PHPUnit

### ISSUE THREAD

**Issue by maks-rafalko** [paratestphp/paratest#624]
| Q | A
| --- | ---
| ParaTest version | 6.3.1
| PHPUnit version | 9.5.8
| PHP version | 8.0.8

Probably related to https://github.com/paratestphp/paratest/pull/481

#### Summary

Running `paratest --version` returns `Console Tool`. It breaks any version parsers and does not provide any helpful information about what Paratest / underlying PHPUnit is used.

To understand the version, I need to do `composer show | grep paratest`.

In additional to that it's not convenient, we also need this in @infection. I'm working on Paratest adapter in order to make it work with Infection.

Under the hood, Infection relies on PHPUnit's version to understand what feature can be used in the generated `phpunit.xml` files. 

#### Current behavior

`paratest --version` returns `Console Tool`

#### Expected behavior

`paratest --version` returns, for example `PHPUnit 9.5.8, Paratest 6.5.3`. If it's not possible, returning `Paratest 6.5.3` would still be helpful.

**Comment by Slamdunk** [comment]
May I ask you what would you use ParaTest version for?
Why not simply ask PHPUnit version only to PHPUnit itself?

**Comment by maks-rafalko** [comment]
1. I want to use it for the purposes as any other tool's version is used for - to know exactly what version is installed (locally, on the CI logs, etc.).
  As [12 Factor CLI Apps](https://medium.com/@jdxcode/12-factor-cli-apps-dd3c227a0e46) say in the `3. What version am I on?` paragraph, all CLI apps should have a command (option) to get the version, you can read the explanation there

  Also, it's very convenient to see lib's version on CI, it helps to better and quicker understand the issue if local lib's version and CI lib's version are different (yes, it happens)

  Moreover, if you run PHPUnit, PHP-CS-Fixer, Infection - all of these libs display their version at the start. So I, as a developer, expect the version to be displayed from Paratest as well.

2. Another reason, when I run Infection with `paratest` adapter, I want to display its version just like we do it for PHPUnit, Pest, PhpSpec and Codeception. But even if we ignore this point, the first one still make sense to me

**Comment by maks-rafalko** [comment]
just checked what Pest does (which is a wrapper around PHPUnit):

```bash
endor/bin/pest --version                                                         
Pest    1.15.0
PHPUnit 9.5.8 by Sebastian Bergmann and contributors.
```

**Comment by Slamdunk** [comment]
So, I'm going to share my thoughts about this topic.
I already know that the following opinions are not agreeable, but I hope you could understand them.

ParaTest version is sort of a lie, there is no version matrix of compatibilities between its version and its dependencies, because process parallelization is a mess, we have plenty of bugs related to specific environments we can't debug nor inspect, and the best we can do is like the email protocol: trying to survive delivering the best value we can.

We don't have the resources to support any other version but the latest one, as [noted in the README.md](https://github.com/paratestphp/paratest#versions), so if you ever encounter a bug with a version that is not the latest we can't help.
We don't have real APIs beside `--wrapper` and `--processes`, so very little can break on this front, while almost everything can break from day to day due to my choice to rely on `@internal` PHPUnit classes.

Would delivering ParaTest version be helpful? Of course, your points are valid.
Would be cost effective to maintain the version internally and update it every release? No, we are not going to help you anyway if you don't use the latest release.

If someone really needs ParaTest version by runtime, I suggest to use https://github.com/Ocramius/PackageVersions

:frowning_face:

**Comment by Jean85** [comment]
I've attempted a solution (that requires no further maintenance on our side) with #668.
