### ISSUE TITLE
The tests passed does not matched the total tests in PHPStorm

### ISSUE THREAD

**Issue by JurianArie** [paratestphp/paratest#750]
| Q | A
| --- | ---
| ParaTest version | 7.1.2
| PHPUnit version | 10.0.19
| PHP version |8.1.15
| PHPStorm version|2022.3

#### Summary

When upgrading I noticed that the PHPStorm integration didn't work as it did before.

#### Current behavior

The tests passed does not matched the total tests in PHPStorm

#### How to reproduce: command, code and error stack trace

<details>
<summary>Screenshots from v6 with Laravel 9</summary>

<img width="564" alt="Screenshot 2023-04-05 at 16 53 46" src="https://user-images.githubusercontent.com/28654085/230120702-ca64c9a6-f0ab-4e85-9cba-eeef07825a20.png">

Screenshot of all the tests passing in CLI

![Screenshot 2023-04-05 at 16 51 16](https://user-images.githubusercontent.com/28654085/230120736-2454eeb4-6f79-44ad-8b14-4dcda155bb74.png)

Screenshot of all tests passing in PHPStorm

</details>

<details>
<summary>Screenshots from v7 with Laravel 10</summary>
<img width="588" alt="Screenshot 2023-04-05 at 16 46 05" src="https://user-images.githubusercontent.com/28654085/230121122-3be396d8-5049-4a8b-b87e-5e2c1504e9db.png">

Screenshot of all the tests passing in CLI

![Screenshot 2023-04-05 at 16 42 22](https://user-images.githubusercontent.com/28654085/230121007-dbac7492-626c-40bd-98c0-2ec32cd4dd1b.png)

Screenshot showing that only 557 of the 582 tests were ran in PHPStorm
</details>

#### Expected behavior

I expect the total tests passed to match the total tests, like in v6

**Comment by Slamdunk** [comment]
Honestly I have no clue :shrug:

**Comment by Lydnasty** [comment]
This happens if one test has a `@depends` of another file's test.
It's completely ignored.

**Comment by axlon** [comment]
> This happens if one test has a `@depends` of another file's test.

I can reproduce this behaviour consistently and don't use that annotation.

I have no understanding of how ParaTest works under the hood, but I'm under the impression that PHPStorm thinks ParaTest is done as soon as the first process finishes (instead of waiting for all of them to finish). I think this because when I run ParaTest with just 2 processes the difference between "passed" and "total" will either be 0 or 1. But when I run it with 8 processes the difference is up to 7 (it fluctuates but I have not seen it go over 7).
