### ISSUE TITLE
paratest_for_phpstorm deadlock issues where not present in command line runner

### ISSUE THREAD

**Issue by robertmarney** [paratestphp/paratest#823]
| Q | A
| --- | ---
| ParaTest version | 6.6.5
| PHPUnit version | 9.5.24
| PHP version | 8.1.25
| PHP Storm Version | 2023.1.3

#### Summary

I have a test suite for a large Laravel application that interacts heavily with a MYSQL database. This test suite works well running Paratrust via the command line, via the PHP Storm plugin I am seeing massive deadlock issues.

#### Current behavior

Via command line (`php artisan test --parallel --processes=4`) I see no deadlock. When this same phpunit.xml file is run via PHP storm using the paratest_for_phpstorm plugin I am seeing roughly 80% failure due to deadlock issues. These deadlock issues are intermittent (every test run the failing test varies)

#### How to reproduce: command, code and error stack trace

Run parallel tests with a number of tests that use database transactions within the underlying code, ensure they work from command line and then in storm and see the same test suite / tests fail due to deadlock

#### Expected behavior

Consistency between command line and paratest_for_phpstorm

**Comment by Slamdunk** [comment]
I cannot work myself on the PHPStorm plugin because it cannot be reproduced here.

I will however merge any well-crafted PR with the fix, if you find any

**Comment by mrozbarry** [comment]
Just commenting to say I _believe_ I'm seeing the same thing with a client's code base. The spinners in PHPStorm never resolve to pass or fail, and re-running failed tests completely ignores these deadlocks. We have about 2.5K tests, with many assertions. It's a private repository, and I haven't been able to reproduce this bug in a smaller code-base.

I initially thought this was just from upgrading from phpunit 9->10 and phpstorm seeing both the old style cache file and new one. I deleted the cache files and re-ran tests, and see the same results, so I think it's safe to rule that out.

Running tests without paratest runs fine in PHPStorm, so I'm not convinced that the issue is in PHPStorm, but it still could be 🤷 .
