### ISSUE TITLE
PHPUnit 11 support

### ISSUE THREAD

**Issue by nunomaduro** [paratestphp/paratest#830]
Hi Paratest team! Wondering if there is plans to implement PHPUnit 11 support soon?

**Comment by Slamdunk** [comment]
Sure, let me come back from vacation first 😉

**Comment by Slamdunk** [comment]
So, from a code perspective, ParaTest's build gets green with few edits on PHPUnit 11, we should be able to ship a release within minutes after PHPUnit 11 is going to come out without problems.

The real issue is [renovate](https://github.com/apps/renovate) lacks support for upgrades on multiple major. Let me expain.
You are well aware that ParaTest uses `@internal` PHPUnit's classes and that caused errors for downstream users when ParaTest didn't catch up in time with PHPUnit's internal changes.
This has been almost gone with the introduction of the dependancy bot: as soon as a new PHPUnit release gets out, the bot runs a build with the new release and if it fails it opens a PR with the issue and I receive an email with a request to fix it.

But this good cycle would break if we're going for `"phpunit/phpunit": "^10 || ^11"`: the bot is not capable of running the build for, let's say, `"phpunit/phpunit": "^10.2.3 || ^11.4.5"` when PHPUnit releases `10.2.3` or `11.4.5`, unfortunately, and so if anything breaks I wouldn't get notified.

My current plan is:

* release ParaTest `v7.4` with support for both PHPUnit 10 and 11 versions
* manually check and upgrade this new minor for a month
* release ParaTest `v7.5` with support for PHPUnit 11 only so `renovatebot` automation can kick in again

**Comment by nunomaduro** [comment]
Perfect! Thanks!

**Comment by nunomaduro** [comment]
PHPUnit 11 ships tomorrow for info: https://github.com/sebastianbergmann/phpunit/blob/83443c7a0266a5afb72c6a3f9bb57a51494359a2/ChangeLog-11.0.md.
